// app/api/submit/route.ts
// Next.js App Router — POST /api/submit
// SMTP-based (nodemailer) — swap provider bằng cách đổi env vars, không sửa code.
// Generated by biz-email-setup

import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

// nodemailer dùng node:net/tls → bắt buộc Node runtime, KHÔNG chạy được trên Edge.
export const runtime = "nodejs";

const SMTP_HOST = process.env.SMTP_HOST!;
const SMTP_PORT = Number(process.env.SMTP_PORT || 587);
const SMTP_SECURE = process.env.SMTP_SECURE === "true"; // true = port 465 SSL, false = port 587 STARTTLS
const SMTP_USER = process.env.SMTP_USER!;
const SMTP_PASS = process.env.SMTP_PASS!;

const MAIL_FROM = process.env.MAIL_FROM || SMTP_USER;
const OWNER = process.env.OWNER_EMAIL!;
const PAGE_URL = process.env.LANDING_PAGE_URL || "";

// Reuse transporter across invocations (warm Lambda). Lazy-init để không crash module load nếu env thiếu khi build.
let transporter: nodemailer.Transporter | null = null;
function getTransporter() {
  if (!transporter) {
    transporter = nodemailer.createTransport({
      host: SMTP_HOST,
      port: SMTP_PORT,
      secure: SMTP_SECURE,
      auth: { user: SMTP_USER, pass: SMTP_PASS },
    });
  }
  return transporter;
}

type LeadPayload = {
  name: string;
  phone: string;
  email: string;
  utm_source?: string;
  utm_campaign?: string;
  message?: string;
};

function validate(data: Partial<LeadPayload>): { ok: true; data: LeadPayload } | { ok: false; error: string } {
  const name = (data.name || "").trim();
  const phone = (data.phone || "").trim();
  const email = (data.email || "").trim().toLowerCase();

  if (!name) return { ok: false, error: "Thiếu họ tên" };
  if (!phone) return { ok: false, error: "Thiếu số điện thoại" };
  if (!/^[0-9+\s().-]{9,15}$/.test(phone)) return { ok: false, error: "Số điện thoại không hợp lệ" };
  if (!email) return { ok: false, error: "Thiếu email" };
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) return { ok: false, error: "Email không hợp lệ" };

  return {
    ok: true,
    data: {
      name,
      phone,
      email,
      utm_source: data.utm_source,
      utm_campaign: data.utm_campaign,
      message: data.message,
    },
  };
}

function formatPhoneVN(phone: string): string {
  const digits = phone.replace(/\D/g, "");
  if (digits.length === 10) return `${digits.slice(0, 4)} ${digits.slice(4, 7)} ${digits.slice(7)}`;
  return phone;
}

function timestampVN(): string {
  const now = new Date();
  return new Intl.DateTimeFormat("vi-VN", {
    timeZone: "Asia/Ho_Chi_Minh",
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(now);
}

// REPLACE these with offer-specific content. Skill will inject from offer.json/copy.json.
const OFFER = {
  product_name: "{{PRODUCT_NAME}}",
  brand_name: "{{BRAND_NAME}}",
  sender_name: "{{SENDER_NAME}}",
  zalo_number: "{{ZALO_NUMBER}}",
};

function renderLeadEmailHTML(lead: LeadPayload): string {
  // Skill replaces this with actual rendered template (see templates/email-confirmation.html)
  return `
<!DOCTYPE html>
<html lang="vi">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${OFFER.product_name}</title>
</head>
<body style="margin:0;padding:0;background:#f5f5f7;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#1a1a1a;">
  <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="background:#f5f5f7;">
    <tr><td align="center" style="padding:32px 16px;">
      <table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="max-width:560px;background:#fff;border-radius:12px;overflow:hidden;">
        <tr><td style="padding:32px 24px;">
          <p style="margin:0 0 16px;font-size:16px;line-height:1.5;">Chào anh/chị ${lead.name},</p>
          <p style="margin:0 0 16px;font-size:16px;line-height:1.5;">
            Em là ${OFFER.sender_name} từ ${OFFER.brand_name}. Em vừa nhận thông tin
            đăng ký của anh/chị về <strong>${OFFER.product_name}</strong>.
          </p>
          <!-- SKILL: thay block dưới đây bằng email pattern P1/P2/P3/P4 đã được user duyệt -->
          <p style="margin:0 0 24px;font-size:16px;line-height:1.5;">
            Em sẽ liên hệ qua số ${formatPhoneVN(lead.phone)} trong vòng 24h tới để hỗ trợ anh/chị.
          </p>
          <p style="margin:24px 0 0;font-size:14px;color:#666;">
            Có gì cần hỗ trợ gấp, anh/chị nhắn Zalo: <strong>${OFFER.zalo_number}</strong>.
          </p>
          <p style="margin:24px 0 0;font-size:14px;color:#666;">
            — ${OFFER.sender_name}<br/>${OFFER.brand_name}
          </p>
        </td></tr>
      </table>
      <p style="margin:16px 0 0;font-size:12px;color:#999;text-align:center;">
        Anh/chị nhận email này vì đã đăng ký tại ${PAGE_URL}.
      </p>
    </td></tr>
  </table>
</body>
</html>`.trim();
}

function renderOwnerEmailHTML(lead: LeadPayload): string {
  return `<pre style="font-family:monospace;font-size:14px;">
Lead mới từ ${PAGE_URL}

────────────────────────────────
Tên:       ${lead.name}
SĐT:       ${formatPhoneVN(lead.phone)}
Email:     ${lead.email}
Source:    ${lead.utm_source || "direct"}
Campaign:  ${lead.utm_campaign || "-"}
Thời gian: ${timestampVN()}
${lead.message ? `Ghi chú:   ${lead.message}` : ""}
────────────────────────────────

Quick actions:
- Gọi:   tel:${lead.phone.replace(/\D/g, "")}
- Zalo:  https://zalo.me/${lead.phone.replace(/\D/g, "")}
- Email: mailto:${lead.email}
</pre>`;
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const result = validate(body);
    if (!result.ok) {
      return NextResponse.json({ ok: false, error: result.error }, { status: 400 });
    }
    const lead = result.data;
    const t = getTransporter();

    const [leadInfo, ownerInfo] = await Promise.all([
      t.sendMail({
        from: MAIL_FROM,
        to: lead.email,
        replyTo: OWNER,
        subject: `${lead.name}, đã ghi nhận đăng ký ${OFFER.product_name}`,
        html: renderLeadEmailHTML(lead),
      }),
      t.sendMail({
        from: MAIL_FROM,
        to: OWNER,
        replyTo: lead.email,
        subject: `🔥 Lead mới — ${lead.name} (${formatPhoneVN(lead.phone)}) — ${OFFER.product_name}`,
        html: renderOwnerEmailHTML(lead),
      }),
    ]);

    // nodemailer trả về { messageId, accepted, rejected, response }. Nếu rejected có item → SMTP từ chối.
    if (leadInfo.rejected.length || ownerInfo.rejected.length) {
      console.error("SMTP rejected:", { lead: leadInfo.rejected, owner: ownerInfo.rejected });
      return NextResponse.json(
        { ok: false, error: "Email service tạm lỗi, anh/chị thử lại sau" },
        { status: 500 },
      );
    }

    return NextResponse.json({ ok: true });
  } catch (err) {
    console.error("/api/submit fatal:", err);
    return NextResponse.json({ ok: false, error: "Lỗi server" }, { status: 500 });
  }
}
