// lib/mailer.ts
//
// Singleton nodemailer transporter cho SMTP. Reuse cùng env vars với biz-email-setup:
//   SMTP_HOST, SMTP_PORT, SMTP_SECURE, SMTP_USER, SMTP_PASS, MAIL_FROM
//
// Thiết kế:
//   - Bulk send với throttle (default 200ms giữa các email — tránh trigger Gmail rate limit
//     hoặc Brevo abuse heuristic).
//   - Helper render nội dung (text/HTML, wrap khung, personalize) nằm ở
//     lib/email-render.ts — module thuần, dùng chung với client preview trong /admin.
//     Re-export lại ở đây để code cũ import từ '@/lib/mailer' vẫn chạy.
//   - Đảm bảo CHỈ chạy trên Node runtime (nodemailer dùng `net`/`tls`).
//
// Generated by biz-admin-leads-dashboard.

import nodemailer, { Transporter } from 'nodemailer';

export {
  escapeHtml,
  textToHtml,
  personalize,
  htmlIsFullDocument,
  stripHtmlToText,
  wrapEmailHtml,
  renderCampaignEmail,
} from './email-render';
export type { BodyFormat } from './email-render';

const SMTP_HOST = process.env.SMTP_HOST;
const SMTP_PORT = Number(process.env.SMTP_PORT || 587);
const SMTP_SECURE = process.env.SMTP_SECURE === 'true';
const SMTP_USER = process.env.SMTP_USER;
const SMTP_PASS = process.env.SMTP_PASS;
const MAIL_FROM = process.env.MAIL_FROM || SMTP_USER || '';

let transporter: Transporter | null = null;

export function getTransporter(): Transporter {
  if (!SMTP_HOST || !SMTP_USER || !SMTP_PASS) {
    throw new Error(
      'SMTP chưa cấu hình. Chạy `/biz-email-setup` trước để wire SMTP_HOST/SMTP_USER/SMTP_PASS vào .env.local.',
    );
  }
  if (!transporter) {
    transporter = nodemailer.createTransport({
      host: SMTP_HOST,
      port: SMTP_PORT,
      secure: SMTP_SECURE,
      auth: { user: SMTP_USER, pass: SMTP_PASS },
    });
  }
  return transporter;
}

// =============================================================================
// Send
// =============================================================================

export type SendResult = { ok: true; messageId: string } | { ok: false; error: string };

export async function sendOne(opts: {
  to: string;
  subject: string;
  html: string;
  text?: string;
  replyTo?: string;
}): Promise<SendResult> {
  try {
    const info = await getTransporter().sendMail({
      from: MAIL_FROM,
      to: opts.to,
      subject: opts.subject,
      html: opts.html,
      text: opts.text,
      replyTo: opts.replyTo,
    });
    return { ok: true, messageId: info.messageId };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err) };
  }
}

export function sleep(ms: number): Promise<void> {
  return new Promise(r => setTimeout(r, ms));
}
