// lib/admin-auth.ts
//
// Shared password check cho /api/admin/* routes.
// Timing-safe compare để chống side-channel attack.
//
// Generated by biz-admin-leads-dashboard.

import { timingSafeEqual } from 'crypto';

export function checkAdminPass(headerPass: string | null): boolean {
  const expected = process.env.ADMIN_PASSWORD;
  if (!expected || !headerPass) return false;
  const a = Buffer.from(expected, 'utf8');
  const b = Buffer.from(headerPass, 'utf8');
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}
