// lib/admin-stats.ts
//
// Dashboard analytics — KPI snapshot + time-series + KPI deltas vs previous period.
// Đọc trực tiếp từ bảng `leads` qua Supabase admin client (service_role bypass RLS).
//
// Triết lý: aggregate hết trong JS thay vì query Postgres nhiều lần.
// Với 1 query SELECT * trong N×2 ngày gần nhất (default 60d cho period=30) thì
// quá nhẹ cho Supabase free tier (<10K rows phổ biến). Tránh complexity của
// SQL aggregation + timezone shifts.
//
// Timezone: tất cả bucket tính theo Asia/Ho_Chi_Minh (UTC+7).
// Generated by biz-admin-leads-dashboard.

import { getSupabaseAdmin } from './supabase-admin';

const VN_TZ_OFFSET_MS = 7 * 60 * 60 * 1000;

export type PeriodDays = 7 | 30 | 90;

export type DashboardData = {
  period: {
    days: PeriodDays;
    label: string;                 // "7 ngày qua" / "30 ngày qua" / "90 ngày qua"
    leads: number;
    paid: number;
    pending: number;
    revenue: number;
    conversionRate: number;        // 0..1
  };
  previousPeriod: {
    leads: number;
    paid: number;
    revenue: number;
    conversionRate: number;
  };
  deltas: {
    leadsPct: number | null;       // null nếu previous = 0 (chia 0)
    paidPct: number | null;
    revenuePct: number | null;
    conversionPoints: number;      // điểm phần trăm tuyệt đối, +/- (vd +3.2 nghĩa là tăng từ 12% lên 15.2%)
  };
  totals: {
    allTimeLeads: number;
    allTimePaid: number;
    allTimeRevenue: number;
  };
  timeseries: TimeBucket[];        // length = days, oldest → newest
  statusBreakdown: { paid: number; pending: number; expired: number };
  recentPayments: RecentPayment[]; // last 5 paid leads in period
};

export type TimeBucket = {
  date: string;        // "YYYY-MM-DD" theo VN tz
  leads: number;       // leads created trong bucket
  paid: number;        // leads paid trong bucket (theo paid_at)
  revenue: number;     // VND
};

export type RecentPayment = {
  orderId: string;
  name: string;
  amount: number;
  paidAt: string;
  productName: string;
};

type LeadRow = {
  order_id: string;
  name: string;
  email: string;
  phone: string;
  product_name: string;
  amount: number;
  status: 'pending' | 'paid' | 'expired';
  created_at: string;
  paid_at: string | null;
  payment_record: { amount?: number } | null;
};

// =============================================================================
// Helpers
// =============================================================================

function toVnDateString(iso: string): string {
  // shift to VN tz then take date part
  const t = new Date(iso).getTime() + VN_TZ_OFFSET_MS;
  return new Date(t).toISOString().slice(0, 10); // "YYYY-MM-DD"
}

function todayVnDateString(): string {
  const t = Date.now() + VN_TZ_OFFSET_MS;
  return new Date(t).toISOString().slice(0, 10);
}

function shiftVnDate(yyyymmdd: string, days: number): string {
  const d = new Date(yyyymmdd + 'T00:00:00Z');
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString().slice(0, 10);
}

function pctDelta(curr: number, prev: number): number | null {
  if (prev === 0) return curr === 0 ? 0 : null;
  return ((curr - prev) / prev) * 100;
}

function leadRevenue(l: LeadRow): number {
  if (l.status !== 'paid') return 0;
  return Number(l.payment_record?.amount ?? l.amount ?? 0);
}

// =============================================================================
// Main entry
// =============================================================================

export async function getDashboardData(days: PeriodDays = 30): Promise<DashboardData> {
  const supabase = getSupabaseAdmin();

  // Pull tất cả leads. Với TTL 7-90 ngày của lib-leads-supabase.ts, lượng row hữu hạn.
  // Nếu sau này lớn, có thể optimize bằng .gte('created_at', startOfPreviousPeriod).
  const { data: rows, error } = await supabase
    .from('leads')
    .select('order_id, name, email, phone, product_name, amount, status, created_at, paid_at, payment_record')
    .order('created_at', { ascending: false });

  if (error) throw new Error(`getDashboardData: leads query failed: ${error.message}`);
  const leads = (rows ?? []) as LeadRow[];

  // Build date keys
  const today = todayVnDateString();
  const startCurr = shiftVnDate(today, -(days - 1));     // ngày đầu của period hiện tại
  const startPrev = shiftVnDate(today, -(days * 2 - 1)); // ngày đầu của period trước
  const endPrev = shiftVnDate(today, -days);             // ngày cuối period trước

  // Init time-series buckets
  const timeseries: TimeBucket[] = [];
  for (let i = days - 1; i >= 0; i--) {
    timeseries.push({ date: shiftVnDate(today, -i), leads: 0, paid: 0, revenue: 0 });
  }
  const bucketByDate = new Map(timeseries.map(b => [b.date, b]));

  // Aggregators
  const totals = { allTimeLeads: leads.length, allTimePaid: 0, allTimeRevenue: 0 };
  const currPeriod = { leads: 0, paid: 0, pending: 0, revenue: 0 };
  const prevPeriod = { leads: 0, paid: 0, revenue: 0 };
  const statusBreakdown = { paid: 0, pending: 0, expired: 0 };
  const paidInPeriod: LeadRow[] = [];

  for (const l of leads) {
    const createdDate = toVnDateString(l.created_at);
    const paidDate = l.paid_at ? toVnDateString(l.paid_at) : null;
    const rev = leadRevenue(l);

    // status breakdown (all time)
    if (l.status === 'paid') statusBreakdown.paid++;
    else if (l.status === 'pending') statusBreakdown.pending++;
    else if (l.status === 'expired') statusBreakdown.expired++;

    if (l.status === 'paid') {
      totals.allTimePaid++;
      totals.allTimeRevenue += rev;
    }

    // current period
    if (createdDate >= startCurr && createdDate <= today) {
      currPeriod.leads++;
      if (l.status === 'pending') currPeriod.pending++;
      const bucket = bucketByDate.get(createdDate);
      if (bucket) bucket.leads++;
    }
    if (paidDate && paidDate >= startCurr && paidDate <= today) {
      currPeriod.paid++;
      currPeriod.revenue += rev;
      paidInPeriod.push(l);
      const bucket = bucketByDate.get(paidDate);
      if (bucket) {
        bucket.paid++;
        bucket.revenue += rev;
      }
    }

    // previous period
    if (createdDate >= startPrev && createdDate <= endPrev) {
      prevPeriod.leads++;
    }
    if (paidDate && paidDate >= startPrev && paidDate <= endPrev) {
      prevPeriod.paid++;
      prevPeriod.revenue += rev;
    }
  }

  const currConv = currPeriod.leads === 0 ? 0 : currPeriod.paid / currPeriod.leads;
  const prevConv = prevPeriod.leads === 0 ? 0 : prevPeriod.paid / prevPeriod.leads;

  // Recent 5 payments (in period, by paid_at desc)
  paidInPeriod.sort((a, b) => (b.paid_at ?? '').localeCompare(a.paid_at ?? ''));
  const recentPayments: RecentPayment[] = paidInPeriod.slice(0, 5).map(l => ({
    orderId: l.order_id,
    name: l.name,
    amount: leadRevenue(l),
    paidAt: l.paid_at!,
    productName: l.product_name,
  }));

  return {
    period: {
      days,
      label: `${days} ngày qua`,
      leads: currPeriod.leads,
      paid: currPeriod.paid,
      pending: currPeriod.pending,
      revenue: currPeriod.revenue,
      conversionRate: currConv,
    },
    previousPeriod: {
      leads: prevPeriod.leads,
      paid: prevPeriod.paid,
      revenue: prevPeriod.revenue,
      conversionRate: prevConv,
    },
    deltas: {
      leadsPct: pctDelta(currPeriod.leads, prevPeriod.leads),
      paidPct: pctDelta(currPeriod.paid, prevPeriod.paid),
      revenuePct: pctDelta(currPeriod.revenue, prevPeriod.revenue),
      conversionPoints: (currConv - prevConv) * 100,
    },
    totals,
    timeseries,
    statusBreakdown,
    recentPayments,
  };
}
